SourceType: mysql
SinkType: elasticsearch

MySQL:
  DSN: "root:rootpass@tcp(localhost:3306)/giftdb?parseTime=true"

Kafka:
  Brokers:
    - "localhost:9092"
  Topic: "giftdb.products"
  GroupID: "gift-sync-group"

Elastic:
  URL: "http://localhost:9200"
  Index: "products"
